export const permissions = [
  {
    name: "Viewer Operations",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      contact: ["read"],
      task: ["read"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read"],
      obligation: ["read"],
    },
  },
  {
    name: "Viewer Finance",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      forecast: ["read"],
      finModel: ["read"],
      transaction: ["read"],
      task: ["read"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read"],
      obligation: ["read"],
      category: ["read"],
    },
  },
  {
    name: "Viewer all domains",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      forecast: ["read"],
      finModel: ["read"],
      transaction: ["read"],
      task: ["read"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read"],
      obligation: ["read"],
      contact: ["read"],
      category: ["read"],
    },
  },
  {
    name: "Member Operations",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      task: ["read", "create", "update", "delete"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read", "create", "update", "delete"],
      obligation: ["read", "create", "update", "delete"],
      contact: ["read", "create", "update", "delete"],
    },
  },
  {
    name: "Member Finance",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      task: ["read", "create", "update", "delete"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read", "create", "update", "delete"],
      obligation: ["read", "create", "update", "delete"],
      forecast: ["read", "create", "update", "delete"],
      finModel: ["read"],
      category: ["read"],
      transaction: ["read", "create", "update", "delete"],
    },
  },
  {
    name: "Member all domains",
    allowedScopesOperations: {
      organization: ["read"],
      element: ["read"],
      forecast: ["read", "create", "update", "delete"],
      finModel: ["read"],
      transaction: ["read", "create", "update", "delete"],
      category: ["read"],
      task: ["read", "create", "update", "delete"],
      member: ["read"],
      reportTemplate: ["read"],
      document: ["read", "create", "update", "delete"],
      obligation: ["read", "create", "update", "delete"],
      contact: ["read", "create", "update", "delete"],
    },
  },
  {
    name: "Admin",
    allowedScopesOperations: {
      organization: ["read", "create", "update"],
      element: ["read", "create", "update", "delete"],
      forecast: ["read", "create", "update", "delete"],
      transaction: ["read", "create", "update", "delete"],
      task: ["read", "create", "update", "delete"],
      document: ["read", "create", "update", "delete"],
      obligation: ["read", "create", "update", "delete"],
      contact: ["read", "create", "update", "delete"],
      finModel: ["read", "create", "update", "delete"],
      category: ["read", "create", "update", "delete"],
      finApiAccount: ["read", "create", "update", "delete", "attach", "detach"],
      finApiConnection: ["read", "create", "update", "delete"],
      reportTemplate: ["read", "create", "update", "delete"],
      vcomConnection: ["read", "create", "update", "delete"],
      vcomLink: ["read", "create", "update", "delete", "attach", "detach"],
      member: ["read", "create", "update", "delete"],
      invite: ["read", "create", "update", "delete"],
      comment: ["read", "create", "update", "delete"],
    },
  },
];
